### PR TITLE
Handle null string in transcript.

### PR DESCRIPTION
**Pull request by prmukherj**
We were getting a null string from server in transcript which was not handled.

### CODE REVIEW

**Comment by seanpearsonuk** [comment]
@prmukherj I have removed the internal link

**Review by seanpearsonuk — APPROVED** [review]

**Comment by seanpearsonuk** [comment]
Great work @prmukherj, thanks

**Comment by prmukherj** [comment]
Thank you @seanpearsonuk. Sorry, forgot about that internal link issue.

**Comment by dnwillia-work** [comment]
> @prmukherj I have removed the internal link

and I removed the mention of the internal ID as well.  It's probably best to put an issue for this sort of thing into the PyFluent repo since it required changes to the library.



> I have added #1505 in relation to this.

I added a link to it under the Development heading on the right.

**Comment by seanpearsonuk** [comment]
> > @prmukherj I have removed the internal link
> 
> and I removed the mention of the internal ID as well. It's probably best to put an issue for this sort of thing into the PyFluent repo since it required changes to the library.
> 
> > I have added #1505 in relation to this.
> 
> I added a link to it under the Development heading on the right.

The linked issue #1506 mentions the Fluent bug by ID (just as I did here). We do this for all bugs in https://github.com/orgs/pyansys/projects/23, which makes defect management easier, without revealing significant information. On the Fluent side, we hyperlink to here, but not the reverse.

**Review by hpohekar — APPROVED** [review]

**Review by mkundu1 — APPROVED** [review]

**Pull request merged**
