### PR TITLE
Implement vale on pyfluent

### PR DESCRIPTION
**Pull request by RobPasMue**
As it is being done in other PyAnsys projects, vale has been implemented. Vale is a linter which eases the review process to the documentation team by detecting common mistakes and forcing the developer to follow the Google styler guidelines when writing the docs.

@PipKat please proceed to solve the existing errors when possible. Thanks in advance!

### CODE REVIEW

**Comment by PipKat** [comment]
After discussing with Roberto, we will await for [PR # 655](https://github.com/pyansys/pyfluent/pull/655) to be merged because it will address many of the Vale guideline exceptions found in his documentation style check. We will then update this Vale branch, which I will use to resolve the remaining issues.

**Comment by PipKat** [comment]
@RobPasMue  I ended up with the Update Branch button on the PR for my overall edit to the pyfluent repo. It brought in your Vale changes, which I didn't expect. I ended up doing the fixes to resolve the issues in my PR.

**Comment by PipKat** [comment]
@dnwillia-work @akaszynski 
I pulled main into Roberto's PR so that it could complete successfully with my Vale issues addressed.

**Comment by RobPasMue** [comment]
Hi @PipKat! From the log of commits in PR #655 it looks like at some point you merged this branch into the PR branch, making my changes already available in the repo. So, it's fine. All this changes are already available in the repository. In fact, this PR will cause 0 changes so let me just close it.

**Pull request closed without merging**
