### PR TITLE
Fix/resolve failing nightly tests (22.2)

### PR DESCRIPTION
**Pull request by prmukherj**
Setting the: "user_creatable = info.get("user_creatable", True)" as True solved the issue locally.

### CODE REVIEW

**Comment by prmukherj** [comment]
Please refer: https://github.com/pyansys/pyfluent/pull/861

**Review by mkundu1 — APPROVED** [review]

**Review by gyeole — APPROVED** [review]

**Comment by seanpearsonuk** [comment]
Hi @prmukherj @mkundu1 are we in the process of opening a Fluent PR for the same change there. With this change, are boundary condition objects still uncreatable?

**Comment by prmukherj** [comment]
@seanpearsonuk , I think @gyeole has done something on the server side associated to this, does that take care of this already?

**Comment by seanpearsonuk** [comment]
@prmukherj are the flobject.py files identical in pyfluent and cortex?

@gyeole @mkundu1

**Pull request merged**
